---
title: GS INTERIOR DESIGN AND MORE
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
email: info@gs-design.be
description: GS Interior design is a full-service interior design studio founded by
  Sona Grigoryan and based in Belgium.
baseurl: ''
url: gs-design.be
plugins:
- jekyll-feed
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
